### ISSUE TITLE
migrate DNS to netlify

### ISSUE THREAD

**Issue by nolessafool** [shift-org/infra#2]
- [x] shift2bikes.org
- [x] shift2bikes.com
- [x] shifttobikes.com
- [x] shifttobikes.org
- [x] pedalpalooza.org

**Comment by onewheelskyward** [comment]
Also take a look at route53- we could manage it all in one place.  We'll have to take in account the mail forwarding.

**Comment by nolessafool** [comment]
current records for shift2bikes.org after they were overwritten by our former webhost (and current DNS host) a second time in 2 years, graphics and text!

```
shift2bikes.org. | 14400 | IN | A | 104.198.14.52
shift2bikes.org. | 14400 | IN | MX | Priority: 0Destination: mail.shift2bikes.org 
mail.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
www.shift2bikes.org. | 14400 | IN | CNAME | shift-docs.netlify.com 
ftp.shift2bikes.org. | 14400 | IN | A | 204.44.192.74 
shift2bikes.org. | 14400 | IN | TXT | v=spf1 +a +mx +ip4:74.85.245.10 ~all
cpcalendars.shift2bikes.org. | 14400 | IN | A | 204.44.192.74 
webdisk.shift2bikes.org. | 14400 | IN | A | 204.44.192.74 
webmail.shift2bikes.org. | 14400 | IN | A | 204.44.192.74 
cpanel.shift2bikes.org. | 14400 | IN | A | 204.44.192.74 
whm.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
cpcontacts.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
default._domainkey.shift2bikes.org. | 14400 | IN | TXT | v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxBcK0IaxlPToIkQJbN8oI3HK7teSLb3vGpbYNjee+ldOr6uOUy8GNvNBALMMUDgO2RHbQafEjDKRxnmS6Kax6M4Jol9XjZCakilQ2vSFcycLNRZ1VB5sLaib/x3DCkPJIfqtzU2mY32sSE1+1MHscRBxVlmxlJYNCo90BFocVFa27i+xkmYQCfC+ZR/mSC59iAv/yKfGLe1eUezQSDk7ju5r2O5iwvH1RDZg8b1TCiJLjHVnzKLWuiokewzGw5XsTXW6uuhAfdRRYuiPsswI9kkxN/pvvP2q/PnJIDHJJtGY4321V7t5eSoK1+SgFv55GBNwrPbPb9D1bXr1UukzjQIDAQAB; 
api.shift2bikes.org. | 14400 | IN | A | 44.231.45.51 
_amazonses.shift2bikes.org. | 14400 | IN | TXT | VaRHdcIDM355mpkTZfgo2res5ppygvsBECqidIEknH8=
d5dtm6bizjlakzu4ur5i43mufc2zy57w._domainkey.shift2bikes.org. | 14400 | IN | CNAME | d5dtm6bizjlakzu4ur5i43mufc2zy57w.dkim.amazonses.com
l6culhmqckz3whzsggiwmltbmma4a7w4._domainkey.shift2bikes.org. | 14400 | IN | CNAME | l6culhmqckz3whzsggiwmltbmma4a7w4.dkim.amazonses.com
b42wfcbnrpjqbi4rlt2rs3hhff6lycff._domainkey.shift2bikes.org. | 14400 | IN | CNAME | b42wfcbnrpjqbi4rlt2rs3hhff6lycff.dkim.amazonses.com
_cpanel-dcv-test-record.shift2bikes.org. | 14400 | IN | TXT | _cpanel-dcv-test-record=26ugZ5U8NxdcQ4qxdwKMSPQDSP2lbi7KeUsXOUta8uHuCLrAAK2crkUMpEeWIzXy
old.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
newshiftapi.shift2bikes.org. | 14400 | IN | A | 54.187.123.121
_d282f2de60268f170901e2555300e2da.old.shift2bikes.org. | 14400 | IN | CNAME | f52ccfdca744e5f9dbdf16f722970b50.70fd1c254b2267ed37167804c66fc806.comodoca.com
cpcalendars.old.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
webdisk.old.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
whm.old.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
cpanel.old.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
webmail.old.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
cpcontacts.old.shift2bikes.org. | 14400 | IN | A | 204.44.192.74
```



![shift-dns-screenshot](https://user-images.githubusercontent.com/229024/92641868-39619700-f294-11ea-8e32-5bdb84778ff9.png)

![shift-dns-screenshot-2](https://user-images.githubusercontent.com/229024/92641863-38306a00-f294-11ea-80d3-afdfdc1f9d68.png)

**Comment by nolessafool** [comment]
(you set these on this page, once you get logged into canvashost:  https://c101.servername.online:2083/cpsess1171602996/frontend/paper_lantern/zone_editor/index.html#/manage?domain=shift2bikes.org - but I think that page is tied to my current SSO session!)

so, the breadcrumbs to get there are:

- login to cpanel (from https://support.canvashost.com/clientarea.php?action=productdetails&id=428)
- select `zone editor`
- select shift2bikes.org (the other ones are not used except to redirect to the main site)

**Comment by nolessafool** [comment]
I've ported all records as of today, 31 Mar 2021, from hostpapa (nee canvashost), to Netlify.  Pedalpalooza.org was taken over by Meghan last year and uses nameservers from her web host, so I didn't migrate it.

What remains is to get logins to the registrars and update the nameservers from these pages:

- https://app.netlify.com/teams/fool/dns/shifttobikes.org#name-servers
- https://app.netlify.com/teams/fool/dns/shift2bikes.org#name-servers
- https://app.netlify.com/teams/fool/dns/shifttobikes.com#name-servers
- https://app.netlify.com/teams/fool/dns/shift2bikes.com#name-servers

**Comment by nolessafool** [comment]
all are migrated!
